### ISSUE TITLE
Bug - Axios Error 524 (try-catch)

### ISSUE THREAD

**Issue by Polabiel** [Polabiel/Quirk#3]
```
/application/src/services/simsimi.ts:45
    throw new Error(error);
          ^
Error: AxiosError: Request failed with status code 524
    at default (/application/src/services/simsimi.ts:45:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at processMessage (/application/src/utils/autoCommand.ts:98:7
```

Ao tentar fazer um comando, ele deu um erro de 524

**Comment by Polabiel** [comment]
this error is solved
